// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcflp7mdbVNWryRoHCvhs2XA8Dhb9FJV8',
    appId: '1:82476075413:web:8a6e2ee74b38911ac78e9c',
    messagingSenderId: '82476075413',
    projectId: 'point-1ca6a',
    authDomain: 'point-1ca6a.firebaseapp.com',
    databaseURL: 'https://point-1ca6a-default-rtdb.firebaseio.com',
    storageBucket: 'point-1ca6a.appspot.com',
    measurementId: 'G-CGVZ9TR3LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS45cz_Int5qm99swq2K2u5fFAn-QpiLQ',
    appId: '1:82476075413:android:6c6f30cd80205d3dc78e9c',
    messagingSenderId: '82476075413',
    projectId: 'point-1ca6a',
    databaseURL: 'https://point-1ca6a-default-rtdb.firebaseio.com',
    storageBucket: 'point-1ca6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOk7GiNaj8z0L0IDyqUWDNDWkEPbcgCXs',
    appId: '1:82476075413:ios:cea276ddf0b3ce3fc78e9c',
    messagingSenderId: '82476075413',
    projectId: 'point-1ca6a',
    databaseURL: 'https://point-1ca6a-default-rtdb.firebaseio.com',
    storageBucket: 'point-1ca6a.appspot.com',
    iosBundleId: 'com.example.evira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOk7GiNaj8z0L0IDyqUWDNDWkEPbcgCXs',
    appId: '1:82476075413:ios:6d4793383884ebb3c78e9c',
    messagingSenderId: '82476075413',
    projectId: 'point-1ca6a',
    databaseURL: 'https://point-1ca6a-default-rtdb.firebaseio.com',
    storageBucket: 'point-1ca6a.appspot.com',
    iosBundleId: 'com.example.evira.RunnerTests',
  );
}
